### PR TITLE
Fix for flames added to non-breaking joints

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Added check for breakForce == 0, if so, then just return

### CODE REVIEW

**Comment by theonegalen** [comment]
Oooh, will this fix non-Squad launchclamps causing flames? Or the Kerbonov droptanks?

**Comment by linuxgurugamer** [comment]
I think so.  I know that JointBreak events are being sent too frequently, what I found was that the breaking force was 0 when no joint was actually broken (in my limited testing).
Would appreciate you testing with known configurations which did have problems

**Comment by theonegalen** [comment]
Is there a way to get a test dll?

**Comment by linuxgurugamer** [comment]
You can download the dll here:  https://github.com/linuxgurugamer/DestructionEffects/releases/tag/LGG

**Comment by theonegalen** [comment]
Thanks. I will test.

**Comment by linuxgurugamer** [comment]
@theonegalen any results on your testing of the DestructionEffects dll?

**Comment by SpannerMonkey** [comment]
@linuxgurugamer  Hi tested your fixes for the annoying unwanted break effects, and by and large it is very successful, except in regards to BDA, In BDA's usage case parts are not destroyed by force, each part is assigned a hit point value and it is the reduction of this hit point pool  to zero which causes the joint to be deactivated, resulting in a break force of 0 (zero)  So parts being destroyed by BDA are not displaying any effects at all. So while it works for non BDA craft in preventing errant FX, it's completely failed in its original purpose of making BDA combat more visual .   I'm not code proficient enough to know if it would be possible to somehow detect BDA turning off a joint  as opposed to a zero break force incident, is it possible.
  Although I've just had another idea ( that i know hasn't been tried yet) that I'll have a word  with JR et al  about 
Thanks for your input on something that's plagued this project since ksp 1.3.1,  if you can think of anything else I'd be happy to test it

**Comment by linuxgurugamer** [comment]
I don't do BDA.  That being said, I suppose an option can be added to detect whether BDA is installed or not, and if it is, to not implement my fix.
Probably would be fairly simple to do, what's the name of the BDA dll?

**Comment by linuxgurugamer** [comment]
@SpannerMonkey 
Here is a new DLL (I'll update the pr) with a chec k for BDA, if it's there, then my fix is ignored
https://github.com/linuxgurugamer/DestructionEffects/releases/tag/test2

**Comment by theonegalen** [comment]
I can actually test this one here in about an hour!

**Comment by theonegalen** [comment]
Seems to work as advertised as long as BD Armory is not installed. :-)

**Comment by linuxgurugamer** [comment]
and if it is installed?

**Comment by theonegalen** [comment]
I don't use BDArmory, so I wouldn't know. Apologies for the miscommunication.

**Comment by linuxgurugamer** [comment]
@SpannerMonkey Can you test my latest changes, please?

**Pull request merged**
